#! /bin/sh

chosen=$(printf "\n\n\n\n󰗽\n" | rofi -dmenu -i -p "" -theme $HOME/.config/rofi/powermenu.rasi)

case "$chosen" in
   "") sudo poweroff ;;
   "") sudo reboot ;;
   "") systemctl suspend-then-hibernate ;;
   "") systemctl hibernate ;;
   "󰗽") bspc quit ;;
   "") betterlockscreen -l ;;
   *) exit 1 ;;
esac

