#! /bin/sh

time_up=$(uptime -p | sed 's/up //g')
chosen=$(echo "\n\n\n󰗽\n\n" | rofi -dmenu -i -p "Uptime: $time_up" -theme $HOME/.config/rofi/powermenu.rasi)

case "$chosen" in
   "") systemctl poweroff ;;
   "") systemctl reboot ;;
   "")
      mpc -q pause
      systemctl suspend
   ;;
   "") systemctl hibernate ;;
   "󰗽") bspc quit ;;
   "") betterlockscreen -l ;;
   *) exit 1 ;;
esac

