#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n󰗽  Log Out\n  Lock" | rofi -dmenu -i -p "")

case "$chosen" in
   "  Power Off") sudo poweroff ;;
   "  Restart") sudo reboot ;;
   "  Suspend") systemctl suspend-then-hibernate ;;
   "  Hibernate") systemctl hibernate ;;
   "󰗽  Log Out") bspc quit ;;
   "  Lock") betterlockscreen -l ;;
   *) exit 1 ;;
esac

