#!/bin/bash

notify-send "Getting list of available Wi-Fi networks..." -u low -t 5000

# Get a list of available wifi connections and morph it into a nice-looking list
wifi_list=$(nmcli --field "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E 's/WPA[0-9] WPA[0-9]|WPA[0-9]//g' | sed -E 's/^--/󰌿/g' | sed '/--/d')

connected=$(nmcli -fields WIFI g)

if [[ "$connected" =~ "enabled" || "$connected" =~ "activado" ]]; then
   toggle="󰖪  Disable WiFi"
fi
if [[ "$connected" =~ "disabled" || "$connected" =~ "desactivado" ]]; then
   toggle="󰖩  Enable WiFi"
fi

chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | rofi -dmenu -i -selected-row 1 -p "WiFi SSID: " )
chosen_id=$(echo "${chosen_network:2}" | xargs)

if [ "$chosen_network" = "" ]; then
   exit 1
elif [ "$chosen_network" = "󰖩  Enable WiFi" ]; then
   nmcli radio wifi on
   notify-send "Enabled" "Wi-Fi was enabled" -u low
elif [ "$chosen_network" = "󰖪  Disable WiFi" ]; then
   nmcli radio wifi off
   notify-send "Disabled" "WiFi was disabled" -u normal
else
   success_message="You are now connected to the WiFi network \"$chosen_id\"."
   saved_connections=$(nmcli -g NAME connection)
   if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
      nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Connection Established" "$success_message"

   else
      if [[ "$chosen_network" =~ "" ]]; then
         wifi_password=$(rofi -dmenu -p "Password: " )
      fi

      nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established" "$success_message"
   fi
fi

