#!/bin/bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

BATTERY_LOW=20
BATTERY_DISCHARGING=$(acpi -b | grep -c "Discharging")
BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')

if [ $BATTERY_DISCHARGING -eq 0 ] && [ $BATTERY_LEVEL -gt 95 ]; then
   notify-send "Full Battery" "Battery Charged" -u low -i "battery-full" -t 5000 -r 9991
elif [ $BATTERY_DISCHARGING -eq 1 ] && [ $BATTERY_LEVEL -lt $BATTERY_LOW ]; then
   notify-send "Low Battery" "Battery Level: $BATTERY_LEVEL%" -u critical -i "battery-alert" -t 30000 -r 9991
fi

